### ISSUE TITLE
Allow Lucene when Admin is not published

### ISSUE THREAD

**Issue by troyfulton** [Kentico/xperience-by-kentico-lucene#45]
So, my general expectation for Lucene is to be able to implement it similar to the way we did in Kentico 12 and below where, we can tell it we want to do screen scraping or structured content searches, define some parameters, define a search results page that uses the settings and viola, search happens.  I had a couple problems when implementing the github version of Lucene, first, it targets .net core 6, however, we’re on .net core 8 and I couldn’t get it working at all.  But I left the code in place, and discovered the admin problem when I later started to working on separating the Admin.
 
So, I’m thinking there is an admin component where we configure how the search will work, info regarding that configuration gets saved in the DB, then when running the site and using search, it would utilize the saved config info in the database and provide the search feature and search results.

Also, since Kentico is suggesting .net core 8, so should this plugin be I would think.

**Comment by michalJakubis** [comment]
Hello Troy,
If I understand correctly, in Kentico 12 you were using built-in smart search based on lucene.net. There was a Smart search application that allowed the user to configure lucene and create indexes. That's pretty much what we're trying to achieve in XbK. In order to do this, we need to depend on Kentico.Xperience.Admin, as this library provides us with the necessary UI framework APIs. In other words, without the Admin library we are unable to achieve what you are used to from the KX12. But what we can do is to separate the UI part of Lucene administration and the logical part. So you will only be left with the APIs, but the configuration and index creation will need to be done programmatically on your end. 

I'm not sure this is what you really want, or am I missing something here?

**Comment by seangwright** [comment]
> first, it targets .net core 6, however, we’re on .net core 8 and I couldn’t get it working at all.

Libraries targeting .NET 6 are compatible with projects targeting .NET 8. In fact, as of today, Xperience by Kentico targets .NET 6 and customers have been able to build their solutions on it with .NET 8 since November of 2023.

If you have an issue using the Lucene library in your project, it isn't going to be related to it target .NET 6.

Also, if you take a look our [.NET 6 support lifecycle policy](https://community.kentico.com/blog/xperience-by-kentico-s-net-support-lifecycle-net-6) blog post, you can see why the Lucene library targets .NET 6 - it was created _before_ .NET 8 was released and since we support .NET 6 customer applications, we did not want to prevent them from using Lucene by targeting .NET 8 with the library.

**Comment by michalJakubis** [comment]
Hi @troyfulton, fix has been released in v6.0.0
https://github.com/Kentico/xperience-by-kentico-lucene/releases
