### ISSUE TITLE
Support indexing media library files to handle site migrations with PDFs

### ISSUE THREAD

**Issue by bluemodus-mwills** [Kentico/xperience-by-kentico-lucene#63]
**Background**
We’re expecting lots of migrations to XbyK. We’re currently helping a customer migrate from Sitecore to XbyK. We also be migrating lots of current customers from KX13 to XbyK. In every case, we’ll be migrating some files to media libraries instead of Content Hub assets. This is because the Xperience Migration Tools migrate files to media libraries.

Customers that have PDF files that need to be searchable, need support for indexing media files. 

**Desired solution**
We’d like the solution to include:
*	An `IndexEventMediaFileModel` that is passed into the `MapToLuceneDocumentOrNull` method if and when a media file is indexed.
*	The ability to add an overload of the `FindItemsToReindex` method that accepts an `IndexEventMediaFileModel` parameter, to allow controlling what media files are indexed. Example:

```
public override async Task<IEnumerable<IIndexEventItemModel>> FindItemsToReindex(IndexEventMediaFileModel changedItem)
{
    return await Task.FromResult(result: new List<IIndexEventItemModel>() { changedItem });
}
```

**Additional context**
This looks very doable in the existing architecture. Something like this?

*	Add an `IndexEventMediaFileModel` for media files based on [IndexEventReusableItemModel](https://github.com/Kentico/xperience-by-kentico-lucene/blob/18362c83df8e7345da246b894615bac52b00c4b0/src/Kentico.Xperience.Lucene.Core/Indexing/IIndexEventItemModel.cs#L112).
*	Add a method `HandleMediaFileEvent` to `DefaultLuceneTaskLogger` based on [HandleReusableItemEvent](https://github.com/Kentico/xperience-by-kentico-lucene/blob/18362c83df8e7345da246b894615bac52b00c4b0/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneTaskLogger.cs#L62).
*	Add events for add, update, & delete of media files to `LuceneSearchModule` based on [HandleContentItemEvent](https://github.com/Kentico/xperience-by-kentico-lucene/blob/18362c83df8e7345da246b894615bac52b00c4b0/src/Kentico.Xperience.Lucene.Core/LuceneSearchModule.cs#L102).
*	For the rebuild index scenario, add enumerating and queuing media files to [DefaultLuceneClient](https://github.com/Kentico/xperience-by-kentico-lucene/blob/18362c83df8e7345da246b894615bac52b00c4b0/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneClient.cs#L21).

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We'll examine it internally and keep you updated on our progress.

**Comment by bluemodus-mwills** [comment]
Thank you, Eva.

**Comment by bkapustik** [comment]
Hello, it would not be difficult to add this feature, we will discuss internally whether Kentico wants to support this feature.
Similiarly to the comment I have left to you in issue the #62 (https://github.com/Kentico/xperience-by-kentico-lucene/issues/62#issuecomment-2282158693) , this would work as follows: In case that a media file is published, deleted or archived the `FindItemsToReindex(IndexEventMediaFileModel changedItem)` method would be called. Similiarly to the reusable items you would return list of all the WebPageItems which are referencing this media file item.

However, the `MapToLuceneDocumentOrNull` method would still only be called with the WebPageItems because on each WebPageItem you can find out whether the media file item is referenced and index it in the returned document. This way every url address gets indexed only once. But you can search for the address via muiltiple properties (any information from the reusable items or media file items) saved in the index / document.

**Comment by bluemodus-mwills** [comment]
@bkapustik - just like the scenario I added to this comment ([#62 comment)](https://github.com/Kentico/xperience-by-kentico-lucene/issues/62#issuecomment-2284542248)) , customers need the ability to index media files without regard to what pages index them. Many customers want PDF files to be separate items in the index and separate items in search results.

This means `MapToLuceneDocumentOrNull` would need to be called for media files so that the media file could be added to the index as a separate Lucene document. You wrote that the method is only called with WebPageItems, but it is called for reusable content items as well, so what I'm asking for fits the current pattern.

**Comment by DavidSlavik** [comment]
We are going to announce the sunset of the Media Library soon. It doesn't make sense to invest in this because of this fact.

We are working on extending the Migration toolkit to support migration from Media Library to Content Hub. @bluemodus-mwills Do I understand it correctly that you won't need this if we help you to migrate ML to CH and invest into [#62 ](https://github.com/Kentico/xperience-by-kentico-lucene/issues/62)?

**Comment by bluemodus-mwills** [comment]
Thank you @DavidSlavik . You are right. If we can migrate Media Library content to the Content Hub, we'd migrate PDFs there and would not need to index the Media Libraries. However, the timing of the new migration capabilities may be a challenge. On a current project, I've already run an initial migration for a Sitecore->XbyK migration and would like to get our dev team started in early September. It would be hard to add the new capabilities to the Sitecore Migration Tool by then, so I would need the team to work without migrated types until the feature is ready. It sounds like a tricky-timing dance.

**Comment by DavidSlavik** [comment]
Closing as the solution will be done as a part of #62
