### ISSUE TITLE
Search Index Flushed During Deployments in SaaS Environment

### ISSUE THREAD

**Issue by MilanLund** [Kentico/xperience-by-kentico-lucene#72]
**Current Setup:**
- **XbyK NuGet packages:** `v29.3.3`  
- **Kentico.Xperience.Lucene NuGet package:** `v8.0.0`

**Issue:**  
I am experiencing an issue where the search index is flushed during deployments to the SaaS environment. I have implemented a simple search functionality using the `Kentico.Xperience.Lucene` package in an XbyK site hosted on SaaS, strictly following the guidance provided in your documentation.

After some deployments, whether to the QA or PROD environment, I notice that the search index loses its entries, requiring a manual rebuild. This behavior does not occur consistently with every deployment, and I have not been able to identify any patterns or triggers that cause it.

**Primary Concern:**  
I am looking for a solution that would ensure the search index entries persist between deployments. One potential approach could be to trigger an automated index rebuild upon application start or on the first request. However, I have not found any relevant guidance in your documentation on this matter. Could you please advise if this could be a reasonable solution, or if I might have overlooked any aspects of the implementation that would ensure the index persists?

**Secondary Concern:**  
I am also considering whether this could be a potential bug on the SaaS side. If I am not mistaken, the index is stored on the file system, which might cause the index files to be lost between deployments. However, since the SaaS environment is a black box, I am unsure about the specifics of what occurs during deployment.

Any insights or guidance on this issue would be greatly appreciated.

**Comment by MilanLund** [comment]
That's unfortunate, but I appreciate you sharing this! Could you clarify what you mean by "rebuild the index after a deployment"? Are you referring to manually rebuilding it in the XbyK UI, or is there a way to do this programmatically, such as on application startup or the first request? If it's possible to automate this, could you point me to any resources for further guidance?

**Comment by seangwright** [comment]
You can use the [ILuceneClient](https://github.com/Kentico/xperience-by-kentico-lucene/blob/v9.0.0/src/Kentico.Xperience.Lucene.Core/Indexing/ILuceneClient.cs#L55) to rebuild the index.

This means you can create a custom ASP.NET Core API endpoint that is protected by AuthN/AuthZ and send a request to it to rebuild the index after a deployment. However, there's no hook/stage in the SaaS deployment process or Xperience where you can place this logic to have it automatically occur after a deployment completes.

Hence...
> We know about the feature gap and the resolution will most likely be in the product or SaaS environment instead of the Lucene integration library.

So, you can log into the Xperience administration after a deployment and rebuild the index by clicking the button in the UI or come up with your own way of triggering it somewhere else.

---

Technically, you could use a db table and assembly versions to keep track of the currently deployed "app version" (not Xperience version) and schedule triggering rebuild if the db app version differs from the assembly app version.

If they differ, you'd update the db and trigger the reindex. Otherwise you skip. This check could run every 1-2 minutes to ensure after a deployment the index is updated.

I've thought about doing this in the Community Portal, which uses this integration and is deployed to Kentico's SaaS, but it's less time cost to just jump into the admin after a deployment and rebuild an index.

**Comment by MilanLund** [comment]
Unfortunately, clicking through the UI isn't very convenient since deploying to SaaS takes around 30 minutes. It's easy to either forget to click afterward or not have the time to wait for it to finish.

As for the technical solution you suggested, it feels a bit over-engineered to me. I was able to implement a simpler approach by handling the [`ApplicationEvents.PostStart` global event](https://docs.kentico.com/developers-and-admins/customization/handle-global-events/reference-global-system-events#applicationevents) and using the [`ILuceneClient`](https://github.com/Kentico/xperience-by-kentico-lucene/blob/v9.0.0/src/Kentico.Xperience.Lucene.Core/Indexing/ILuceneClient.cs#L55) you mentioned. Feel free to check out [the code in the gist](https://gist.github.com/MilanLund/16c26046b2fa0ed16970be617707b219) and let me know if you spot any potential issues. I deployed it to SaaS, and it worked well.

![image](https://github.com/user-attachments/assets/1c8ba854-335a-4ca4-810a-3b7126b35065)

**Comment by seangwright** [comment]
The problem with [ApplicationEvents.PostStart](https://docs.kentico.com/developers-and-admins/customization/handle-global-events/reference-global-system-events#applicationevents) is that it will fire when the app pool recycles, so you'll potentially be rebuilding the search index multiple times a day and you won't be in control of when it rebuilds.

**Comment by MilanLund** [comment]
Oh, I didn't realize that! It would be great if [the documentation](https://docs.kentico.com/developers-and-admins/customization/handle-global-events/reference-global-system-events#applicationevents) included a warning about it. Since there doesn't seem to be a better option in my opinion, I'll stick with this approach for now and keep an eye on things. The index is pretty small, so I don't expect any major performance or other issues.

**Comment by seangwright** [comment]
Some web server set ups don't let the app spin down (and save resources) and instead will keep it "hot" forever, so whether or not that event is triggered multiple times after a deployment depends on the hosting set up.

You can submit some feedback on the docs page if you'd like a little more context added to the event description.

**Comment by MilanLund** [comment]
Thank you for your assistance and the information. I think we're good to close this one."
